runtime: custom
service: chatagent
env: flex

entrypoint: python manage.py start

# Environment variables should be set via .env file or deployment configuration
# See .env.example for required variables

# Add runtime configuration
runtime_config:
  python_version: "3.9"

# Removed image configuration (not supported by App Engine Flex)

liveness_check:
  initial_delay_sec: 300
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 4
  success_threshold: 1

# Add manual scaling to ensure proper updates
manual_scaling:
  instances: 1

# env_variables:
#   MY_API_KEY: 'your_api_key_value'
#   ANOTHER_VARIABLE: 'another_value'

# Optional: Add network settings if needed, e.g., for VPC access
# network:
#   session_affinity: true # Example

# Optional: Define resources (Flex defaults are often more generous than Standard F1)
# resources:
#   cpu: 1
#   memory_gb: 2
#   disk_size_gb: 10

# Automatic scaling is the default for Flex. You can add settings here if needed.
# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 5
#   cpu_utilization:
#     target_utilization: 0.6 